// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojxaukrrgianrbwfwczi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qeGF1a3JyZ2lhbnJid2Z3Y3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzY1MDMsImV4cCI6MjA3NDcxMjUwM30.BYDuwpKdHGyYezHZOR1ISUlF3tcT3sGFTMDqdanqlmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});